## leetcode

In [ ]:
import struct

def big_endian_to_little_endian(big_endian_num):
    # 将整数转换为字节，使用'>I'格式符表示大端无符号整数
    big_endian_bytes = struct.pack('>I', big_endian_num)
    # 将字节解包为整数，使用'I'格式符表示小端无符号整数
    little_endian_num = struct.unpack('I', big_endian_bytes)[0]
    return little_endian_num

# 示例
big_endian_num = 0x12345678  # 大端整数
little_endian_num = big_endian_to_little_endian(big_endian_num)
print(f'大端: {hex(big_endian_num)} -> 小端: {hex(little_endian_num)}')


大端: 0x12345678 -> 小端: 0x78563412


In [ ]:
def big_endian_to_little_endian(big_endian_num):
    # 将整数转换为字节
    big_endian_bytes = big_endian_num.to_bytes(4, 'big')
    # 反转字节序
    little_endian_bytes = big_endian_bytes[::-1]
    # 将字节解包为整数
    little_endian_num = int.from_bytes(little_endian_bytes, 'big')
    return little_endian_num

# 示例
big_endian_num = 0x12345678  # 大端整数
little_endian_num = big_endian_to_little_endian(big_endian_num)
print(f'大端: {hex(big_endian_num)} -> 小端: {hex(little_endian_num)}')


大端: 0x12345678 -> 小端: 0x78563412


In [ ]:
# if len(s)!=len(t):
#     return False
s = "anagram"
t = "nagaram"
s_dic={}
t_dic={}
for i in range(len(s)):
    if s[i] in s_dic.keys():
        s_dic[s[i]]=s_dic[s[i]]+1
    else:
        s_dic[s[i]]=1
    if t[i] in t_dic.keys():
        t_dic[t[i]]=t_dic[t[i]]+1
    else:
        t_dic[t[i]]=1 

In [ ]:
re={}
res=[]
nums = [-1,0,1,2,-1,-4]
for i in range(len(nums)):
    for j in range(i+1,len(nums)):
        k=nums[i]+nums[j]
        if k in re.keys():
            re[k].append([i,j])
        else:
            re[k]=[]
            re[k].append([i,j])
for m in range(len(nums)):
    if -nums[m] in re.keys():
        for n in range(len(re[-nums[m]])):
            if m not in re[-nums[m]][n]:
                mid=re[-nums[m]][n][:]
                mid.append(m)
                res.append(mid)
result=[]
k=[]
for i in range(len(res)):
    for j in res[i]:
        k.append(nums[j])
    if sorted(k) not in result:
        result.append(sorted(k))
    k=[]
result

[[-1, 0, 1], [-1, -1, 2]]

In [ ]:
# 定义IP的数量和它们之间的连接
ips = ['IP1', 'IP2', 'IP3']
connections = {
    ('IP1', 'IP2'): 2,
    ('IP1', 'IP3'): 1,
    ('IP2', 'IP3'): 3,
}

# 创建一个矩阵，大小足够容纳所有IP
# 矩阵的初始值设为0
max_ip_number = max([int(ip[2:]) for ip in ips])  # 假设IP的命名是IP1, IP2, ...
matrix_size = max_ip_number 
soc_matrix = [[0 for _ in range(matrix_size)] for _ in range(matrix_size)]

# 填充矩阵
for (ip1, ip2), speed in connections.items():
    # 将IP名称转换为数字（例如IP1转换为1）
    ip1_number = int(ip1[2:])
    ip2_number = int(ip2[2:])
    
    # 在矩阵中设置传输速度
    soc_matrix[ip1_number - 1][ip2_number - 1] = speed
    soc_matrix[ip2_number - 1][ip1_number - 1] = speed  # 假设连接是双向的

# 输出矩阵
for row in soc_matrix:
    print(row)


[0, 2, 1]
[2, 0, 3]
[1, 3, 0]


In [ ]:
soc_matrix

[[0, 2, 1, 0], [2, 0, 3, 0], [1, 3, 0, 0], [0, 0, 0, 0]]

In [ ]:
def create_soc_matrix(ips):
    # 计算矩阵的大小，使得矩阵为正方形
    size = int(len(ips) ** 0.5)
    if size * size < len(ips):
        size += 1

    # 初始化矩阵，用0填充
    soc_matrix = [[0 for _ in range(size)] for _ in range(size)]

    # 填充矩阵
    for i, ip in enumerate(ips):
        row, col = divmod(i, size)
        soc_matrix[row][col] = ip

    return soc_matrix

# 定义IP列表
ips = [1, 2, 3, 4, 5, 6]

# 创建SoC矩阵
soc_matrix = create_soc_matrix(ips)

# 输出矩阵
for row in soc_matrix:
    print(row)


[1, 2, 3]
[4, 5, 6]
[0, 0, 0]


In [ ]:
import networkx as nx

# 创建一个图
G = nx.Graph()

# 添加节点（IPs）到图中，这里假设有IP1, IP2, IP3, IP4, IP5, IP6
ips = ['IP1', 'IP2', 'IP3', 'IP4', 'IP5', 'IP6']
for ip in ips:
    G.add_node(ip)

# 添加边（传输速度）到图中，这里假设边是双向的，速度为1, 2, 3, 4, 5, 6
edges = [('IP1', 'IP2', 1), ('IP1', 'IP3', 2), ('IP2', 'IP3', 3), ('IP3', 'IP4', 4), ('IP4', 'IP5', 5), ('IP5', 'IP6', 6)]
for src, dest, speed in edges:
    G.add_edge(src, dest, weight=speed)

# 获取节点的布局，这里使用spring layout作为示例
layout = nx.spring_layout(G)

# 创建一个矩阵来表示SoC的布局
# 矩阵的大小为节点数量的平方根的向上取整
matrix_size = int(nx.number_of_nodes(G) ** 0.5) + 1
soc_matrix = [[0 for _ in range(matrix_size)] for _ in range(matrix_size)]

# 填充矩阵
for ip, (x, y) in layout.items():
    # 将IP名称转换为数字（例如IP1转换为1）
    ip_number = int(ip[2:]) - 1
    
    # 计算矩阵中的行和列
    row, col = int(y * matrix_size), int(x * matrix_size)
    
    # 如果行或列超出了矩阵的范围，则进行调整
    row = min(row, matrix_size - 1)
    col = min(col, matrix_size - 1)
    
    # 在矩阵中设置IP的编号
    soc_matrix[row][col] = ip_number + 1

# 输出矩阵
for row in soc_matrix:
    print(row)


[4, 0, 0]
[1, 0, 6]
[0, 5, 2]


# chiplet高可重用性

In [2]:
import numpy as np

# 给定的矩阵
matrix = [
    [3, 2, 2, 3],
    [2, 1, 1, 2],
    [2, 1, 1, 2],
    [3, 2, 2, 3]
]
def Reusability_calculation(matrix,submatrix_row,submatrix_col):

    # 将矩阵转换为numpy数组
    matrix_np = np.array(matrix)

    # 初始化最大重用性和最佳子矩阵
    max_reusability = 0
    best_submatrix = None

    # 遍历矩阵中的每个位置，作为子矩阵的左上角
    for row in range(len(matrix) - submatrix_row + 1):
        for col in range(len(matrix[0]) - submatrix_col + 1):
            # 提取子矩阵
            submatrix = matrix_np[row:row+submatrix_row, col:col+submatrix_col]
            
            # 计算子矩阵在矩阵中的出现次数
            count = 0
            for i in range(len(matrix) - submatrix_row + 1):
                for j in range(len(matrix[0]) - submatrix_col + 1):
                    # 比较当前块和子矩阵
                    if np.all(matrix_np[i:i+submatrix_row, j:j+submatrix_col] == submatrix):
                        count += 1
                    # 比较当前块和子矩阵的旋转版本
                    if np.all(matrix_np[i:i+submatrix_row, j:j+submatrix_col] == np.rot90(submatrix, k=1)):
                        count += 1
                    if np.array_equal(np.rot90(submatrix,k=1),np.rot90(submatrix,k=3))!=True:
                        if np.all(matrix_np[i:i+submatrix_row, j:j+submatrix_col] == np.rot90(submatrix, k=2)):
                            count += 1
                        if np.all(matrix_np[i:i+submatrix_row, j:j+submatrix_col] == np.rot90(submatrix, k=3)):
                            count += 1
                    # 比较当前块和子矩阵的翻转版本
                    # if np.all(matrix_np[i:i+submatrix_row, j:j+submatrix_col] == np.fliplr(submatrix)):
                    #     count += 1
                    # if np.all(matrix_np[i:i+submatrix_row, j:j+submatrix_col] == np.flipud(submatrix)):
                    #     count += 1
            
            # 如果出现次数大于当前最大重用性，则更新最大重用性和最佳子矩阵
            if count > max_reusability:
                max_reusability = count
                best_submatrix = submatrix

    # 输出最大重用性的子图
    print("Most reusable submatrix:")
    print(best_submatrix)
    print("Reusability:", max_reusability)
    return best_submatrix,max_reusability
def Coverage(matrix,submatrix,reusability):
    matrix_area=len(matrix)*len(matrix[0])
    submatrix_area=len(submatrix)*len(submatrix[0])*reusability
    cover=submatrix_area/matrix_area
    return cover
submatrix,reusability=Reusability_calculation(matrix,2,2)
Coverage(matrix,submatrix,reusability)

Most reusable submatrix:
[[3 2]
 [2 1]]
Reusability: 4


1.0

In [3]:
Reusability_calculation(matrix,2,1)

Most reusable submatrix:
[[3]
 [2]]
Reusability: 4


(array([[3],
        [2]]),
 4)

In [ ]:
a=np.matrix([[2,2],[3,3]])
print(a.T)
print(np.rot90(a, k=1))
print(np.rot90(a, k=2))
print(np.rot90(a, k=3))


[[2 3]
 [2 3]]
[[2 3]
 [2 3]]
[[3 3]
 [2 2]]
[[3 2]
 [3 2]]


In [16]:
def Irregular_compare(matrix1,matrix2):
    for i in range(len(matrix1)):
        for j in range(len(matrix1[0])):
            if matrix2[i][j]==0:
                continue
            if matrix2[i][j]!=0 and matrix1[i][j]!=matrix2[i][j]:
                return 0
    return 1
# 选择的子模板的ip数不应该大于模板图ip总数的一半
# 子模版的ip数分为多个数的和，不能超过模板的行列宽
def partition_number(n, k):
    def backtrack(remaining, parts):
        if len(parts) == k:
            if remaining == 0:
                result.append(parts[:])
            return
        for i in range(1, remaining + 1):
            if len(parts) + 1 <= k:
                parts.append(i)
                backtrack(remaining - i, parts)
                parts.pop()
    
    result = []
    backtrack(n, [])
    return result
def sum_partition(target,split_thresold,number_thresold):
    sum_p=[]
    for i in range(2,split_thresold+1):
        sum_p.append(partition_number(target,i))
    # 使用嵌套循环遍历列表，并根据条件删除子列表
    for sublist in sum_p[:]:  # 创建 list1 的副本以避免在遍历时修改列表
        for subsublist in sublist[:]:  # 创建 sublist 的副本以避免在遍历时修改列表
            if any(element > number_thresold for element in subsublist):
                sublist.remove(subsublist)
                continue  # 删除子列表后跳出内层循环
    sum_p = [sublist for sublist in sum_p if sublist]
    for sublist in sum_p[:]:
        for subsublist in sublist[:]:
            if all_elements_same(subsublist):
                sublist.remove(subsublist)
                continue
    return sum_p
# 判断列表是否全是一样的元素
def all_elements_same(lst):
    # 检查列表是否为空
    if not lst:
        return False
    # 检查列表中的每个元素是否都与第一个元素相等
    return all(element == lst[0] for element in lst)       

In [5]:
m1=[[3,2],[2,1]]
m2=[[3,2],[2,0]]
Irregular_compare(m1,m2)

# Example usage:
n = 5
k = 4
partitions = partition_number(n, k)
for partition in partitions:
    print(partition)

[1, 1, 1, 2]
[1, 1, 2, 1]
[1, 2, 1, 1]
[2, 1, 1, 1]


In [14]:
# 假设 list1 是包含嵌套子列表的列表
list1 = [[[1, 4], [2, 3], [3, 2], [4, 1]],
         [[1, 1, 3], [1, 2, 2], [1, 3, 1], [2, 1, 2], [2, 2, 1], [3, 1, 1]],
         [[1, 1, 1, 2], [1, 1, 2, 1], [1, 2, 1, 1], [2, 1, 1, 1]]]
for sublist in list1[:]:  # 创建 list1 的副本以避免在遍历时修改列表
    for subsublist in sublist[:]:  # 创建 sublist 的副本以避免在遍历时修改列表
        if any(element > 2 for element in subsublist):
            sublist.remove(subsublist)
            continue  # 删除子列表后跳出内层循环

list1 = [sublist for sublist in list1 if sublist]

print(list1)


[[[1, 2, 2], [2, 1, 2], [2, 2, 1]], [[1, 1, 1, 2], [1, 1, 2, 1], [1, 2, 1, 1], [2, 1, 1, 1]]]


In [18]:


# 示例
my_list = [1, 1, 1, 1, 1]
print(all_elements_same(my_list))  # 输出: True

my_list = [1, 1, 2, 1, 1]
print(all_elements_same(my_list))  # 输出: False


True
False


In [19]:
list2=[[[4, 4], [3, 3], [3, 2], [4, 1]],
 [[1, 1, 1], [2, 2, 2], [3, 3, 3], [2, 1, 2], [2, 2, 1], [3, 1, 1]],
 [[1, 1, 1, 1], [1, 1, 2, 1], [1, 2, 1, 1], [2, 1, 1, 1]]]

for sublist in list2[:]:
    for subsublist in sublist[:]:
        if all_elements_same(subsublist):
            sublist.remove(subsublist)
            continue
print(list2)

[[[3, 2], [4, 1]], [[2, 1, 2], [2, 2, 1], [3, 1, 1]], [[1, 1, 2, 1], [1, 2, 1, 1], [2, 1, 1, 1]]]


In [26]:
# 假设 matrix 和 list1 已经被定义
matrix = [
    [3, 2, 2, 3],
    [2, 1, 1, 2],
    [2, 1, 1, 2],
    [3, 2, 2, 3]
]
list1 = [[[1, 4], [2, 3], [3, 2], [4, 1]],
         [[1, 1, 3], [1, 2, 2], [1, 3, 1], [2, 1, 2], [2, 2, 1], [3, 1, 1]],
         [[1, 1, 1, 2], [1, 1, 2, 1], [1, 2, 1, 1], [2, 1, 1, 1]]]
for sublist in list1:
    for subsublist in sublist:
        res=[[0]*max(subsublist)]*len(subsublist)
        for i in range(len(subsublist)):
            
            

In [35]:
matrix = [
    [3, 2, 2, 3],
    [2, 1, 1, 2],
    [2, 1, 1, 2],
    [3, 2, 2, 3]
]
list1 = [[1, 4], [2, 3], [3, 2], [4, 1]]
res=[]
def Generate_initial_matrix(row,col):
    res=[[0]*row]*col
    return res
# list的长度要大于row_wid
def extract_elements(list,ip_number,row_wid):
    res=[]
    for i in range(row_wid):
        temp=[0]*row_wid
        for j in range(ip_number):
            if i+ip_number<=len(list):
                temp[i:i+ip_number]=list[i:i+ip_number]
            else:
                break
            res.append(temp)
    return res
def Subgraph_extraction(matrix,list):
    

extract_elements(matrix[0],list1[0][1],list1[0][1])

[[3, 2, 2, 3], [3, 2, 2, 3], [3, 2, 2, 3], [3, 2, 2, 3]]